Cadc 12067 Use number of cores instead of millicores ('m') and use 'T', 'G', 'M', 'K' instead of 'Ti', 'Gi', 'Mi', 'Ki'
opencadc/science-platform pull request #420
Opened 2022-12-19 20:10 UTC by yeunga

2023-01-12 20:14 UTC, brianmajor requested changes
@yeunga I would like to see some unit tests for these conversion functions.  It would be easier to understand what they're doing, and since they're so isolated, they make good candidates for unit tests.  You can make the method signatures non-private where needed to make them visible to the test code.  Only write them for ones that don't require kubernetes interaction.

2023-01-16 17:40 UTC, yeunga commented
@brianmajor A unit test has been added.

2023-01-16 21:22 UTC, brianmajor commented
@shinybrar - FYI: once merged, this PR will change how the units of RAM and CPU are shown in both the per-session and global stats.  Let us know if you want a heads up before the release so that we don't break your skaha client.

2023-01-20 23:00 UTC, brianmajor approved these changes

2023-01-20 23:00 UTC, merged