Cadc 12189 update renew algorithm to accommodate different activeDeadlineseconds in skaha.sessionexpiry values
opencadc/science-platform pull request #431
Opened 2023-01-25 01:03 UTC by yeunga

- for preliminary review
- implementation to be tested

2023-01-26 21:06 UTC, hjeeves requested changes
Sounds like just the k8sUtil imports should be walked back.

2023-01-26 21:06 UTC, hjeeves commented on skaha/src/main/java/org/opencadc/skaha/K8SUtil.java
> +import java.util.HashMap;
Are these imports needed?

2023-01-26 21:06 UTC, hjeeves commented on skaha/src/main/java/org/opencadc/skaha/K8SUtil.java
> +import java.util.HashMap;
Other than those imports, it seems good.

2023-01-31 18:34 UTC, yeunga commented on skaha/src/main/java/org/opencadc/skaha/K8SUtil.java
> +import java.util.HashMap;
Removed unnecessary Imports.

2023-02-06 21:27 UTC, hjeeves approved these changes
Looks good! Thanks for updating the integration tests.

2023-02-09 22:41 UTC, brianmajor approved these changes

2023-02-09 22:41 UTC, merged