Add extraHosts support to posix mapper, following local convention
opencadc/science-platform pull request #653
Opened 2024-07-10 14:44 UTC by daikema

When attempting to setup the POSIX mapper I was having errors reaching my local registry and discovered that that was due to the hostname I was using resolving to the local loopback address and thus wasn't functioning from within a pod.

Most of the other charts had support for adding host aliases, so I've added the same for the posix mapper helm chart following the conventions from the other charts in the repo.

2024-07-16 14:00 UTC, at88mph requested changes

2024-07-16 14:00 UTC, at88mph commented on deployment/helm/posix-mapper/templates/posix-mapper-tomcat-deployment.yaml
> +    {{- end }}
There's actually a bug with this that will be fixed in the next release in the other deployments, so we'll need the same fix here.  The `range` will add multiple `hostAliases` stanzas, but only one is allowed, with an array of entries.  So the `range` needs to be _inside_ the `hostAliases` entry, but only if some were specified.  It should look like:

```yaml
{{- with .Values.deployment.extraHosts }}
      hostAliases:
{{- range $extraHost := . }}
        - ip: {{ $extraHost.ip }}
          hostnames:
            - {{ $extraHost.hostname }}
{{- end }}            
{{- end }}
```

2024-07-16 17:12 UTC, brianmajor commented
The main issue with this approach is that skaha assumes knowledge and makes use of the cavern mount--something we're trying to get away from.  

The currently released version, though not portable, seems to be performing well.  I think something similar to that design is ideal.  Having a container that does the merge be based on cadc-java would be an improvement.

2024-07-16 17:21 UTC, daikema commented
@at88mph are you able to add that change you suggested here?  I'm currently on leave.

2024-07-16 17:26 UTC, at88mph commented
> The main issue with this approach is that skaha assumes knowledge and makes use of the cavern mount--something we're trying to get away from.
> 
> The currently released version, though not portable, seems to be performing well. I think something similar to that design is ideal. Having a container that does the merge be based on cadc-java would be an improvement.

I think you meant for this to go into #652, @brianmajor?

2024-07-16 17:27 UTC, at88mph commented
Sure thing, @daikema .

2024-07-24 15:58 UTC, at88mph approved these changes

2024-07-24 15:59 UTC, merged