Configure ephemeral storage.
opencadc/science-platform pull request #677
Opened 2024-08-02 17:34 UTC by at88mph

Relies on https://github.com/opencadc/science-platform/pull/676.

Includes clean up and better documentation.  Also includes a minor version change as it will be incompatible.

Merge `main` once #676 is merged.

2024-08-06 19:22 UTC, SharonGoliath submitted a review, later dismissed

2024-08-29 22:52 UTC, brianmajor commented
Hi @at88mph - What story is this PR for?

2024-08-30 14:40 UTC, at88mph commented
@brianmajor It's for [CADC-13545](https://cadc-ccda.atlassian.net/browse/CADC-13545).

2024-09-10 22:23 UTC, brianmajor requested changes
Some comments and suggestions, most not actually related to the intent of the PR!

2024-09-10 22:23 UTC, brianmajor commented on deployment/helm/skaha/sample-local-values.yaml
> +    # Change this to enable a GPU, if one is present on a Node
```suggestion
    # When set to 'true' this flag will enable GPU node scheduling.
```

2024-09-10 22:23 UTC, brianmajor commented on deployment/helm/README.md
> +    # skahaTld: "/cavern"
I know it's not related to this PR, but I wonder if cavernRoot would have been a better name.
But also, what is this used for?  I know we're trying to decouple skaha and storage altogether, but I guess this field is used in the few references remaining?

2024-09-10 22:23 UTC, brianmajor commented on deployment/helm/skaha/sample-local-values.yaml
> +    skahaTld: "/cavern"
Same comment here... cavernRoot?

2024-09-10 22:23 UTC, brianmajor commented on deployment/helm/skaha/sample-local-values.yaml
> +      maxEphemeralStorage: "100Gi" # Max expansion for ephemeral storage (scratch disk space)
This area is nice and tidy.

2024-09-11 17:23 UTC, brianmajor approved these changes

2024-09-11 17:23 UTC, merged