[CADC-13816] Implement linting and style checks
opencadc/science-platform pull request #724
Opened 2024-11-06 23:25 UTC by shinybrar

- Changed style format from `cadc-quality` to `palantir-java-format`
- Changed formatting / lint engine from `checkStyle` to `spotless`
- Added checking for `yaml|java|gradle` file formats.
- Fixed excessive token permission issues for codeQL action

2024-11-06 23:47 UTC, at88mph requested changes

2024-11-06 23:47 UTC, at88mph commented on skaha/build.gradle
> +    id("com.diffplug.spotless") version "6.25.0"
Just for consistency, please match this to the others:
```groovy
id 'com.diffplug.spotless' version '6.25.0'
```

2024-11-07 16:40 UTC, at88mph approved these changes

2024-11-07 16:42 UTC, at88mph requested changes

2024-11-07 16:42 UTC, at88mph commented on .github/workflows/ci.linting.yml
> +        uses: actions/setup-java@v2
This is at version 4 as well.  Please bump it.

2024-11-07 16:42 UTC, at88mph commented on .github/workflows/ci.testing.yml
> +        uses: actions/setup-java@v2
This is at version 4 as well. Please bump it.

2024-11-08 18:51 UTC, at88mph submitted a review, later dismissed

2024-11-08 18:51 UTC, at88mph submitted a review, later dismissed

2024-11-08 19:22 UTC, shinybrar commented
Fixes CADC-13811, CADC-13812 and CADC-13816

2024-11-08 19:55 UTC, at88mph requested changes

2024-11-08 19:55 UTC, at88mph commented on skaha/opencadc.gradle
> -    intTestImplementation.extendsFrom testImplementation
The `intTestImplementation` still needs to be there to run the integration tests.

2024-11-08 21:14 UTC, at88mph approved these changes

2024-11-08 21:15 UTC, merged