Ct 186 Rename 'Terminate'
opencadc/science-platform pull request #87
Opened 2020-08-11 00:14 UTC by yeunga

2020-08-17 16:32 UTC, brianmajor commented on software-containers/arcade-casa/version-3.4-4.2/startup.sh
> -/arcade/update-data.patch /opt/casa
I'm probably not up to date on this but just wondering why update-data.patch has been removed...

2020-08-20 16:31 UTC, brianmajor requested changes
The make process creates all the scripts that go into /usr/local/bin, so don't create custom ones.

The title of the xterm is being handled by the arcade service, so if there are any curl commands that post a param that is intented to be the title, please remove them.  I don't think there are any special differences between any of the launching scripts so their creation on make is the same.

2020-08-20 16:31 UTC, brianmajor commented on session-containers/arcade-desktop/software-scripts/nifty.sh
> +#!/bin/bash
These scripts are created automatically on make, so please delete this file.

2020-08-20 16:31 UTC, brianmajor commented on session-containers/arcade-desktop/software-scripts/Gemini-DRAGONS.sh
> +#!/bin/bash
These scripts are created automatically on make, so please delete this file.

2020-08-20 16:31 UTC, brianmajor commented on session-containers/arcade-desktop/arcade-software.properties
> +niri = nat1405/niri:0.1
Isn't one of these supposed to be named Gemini-DRAGONS now?

2020-08-21 21:44 UTC, yeunga commented on software-containers/arcade-casa/version-3.4-4.2/startup.sh
> -/arcade/update-data.patch /opt/casa
The update-data.patch was suggested by CASA in its out-of-date document to fix the leap second issue. We are using /cavern/projects/casa-data-repository. The patch file is not needed anymore.

2020-08-21 21:49 UTC, yeunga commented on session-containers/arcade-desktop/software-scripts/nifty.sh
> +#!/bin/bash
The generated nifty.sh uses param and that was the reason for the start up failure. I suppose I can add another template and add some conditional code in create-software-links.sh to generate nifty.sh correctly. Just let me know if you prefer adding another template.

2020-08-21 21:50 UTC, yeunga commented on session-containers/arcade-desktop/arcade-software.properties
> +niri = nat1405/niri:0.1
Updated niri to Gemini-DRAGONS.

2020-08-21 21:57 UTC, yeunga commented
Currently create-software-links.sh uses software-sh.template to generall the .sh files. Hence all generated .sh files use param except for the custom .sh files. xterm, nifty and Gemini-DRAGONS use their own custom .sh files.

2020-08-21 22:14 UTC, yeunga commented on session-containers/arcade-desktop/software-scripts/Gemini-DRAGONS.sh
> +#!/bin/bash
ditto

2020-09-23 15:42 UTC, brianmajor approved these changes

2020-09-23 15:42 UTC, merged